name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests (Jest)
        working-directory: ./backend
        run: npm test

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests (Jest)
        working-directory: ./frontend
        run: npm test

      - name: Run Cypress E2E tests
        working-directory: ./frontend
        run: npx cypress run --browser chrome

      - name: Deploy to Render (solo si todo pasa)
        run: echo "✅ Aquí podrías agregar despliegue automático si tienes configurado Render o Heroku"
